---
#----------------------------------------------
# ConfigMap - Biến môi trường cho API
#----------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: khuetuan-config
  namespace: khuetuan
  labels:
    app: khuetuan
    component: config
data:
  DATABASE_URL: "postgresql://khuetuan:123456@14.241.251.180:5002/khuetuandb"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_cG9saXNoZWQtZ2xvd3dvcm0tOTEuY2xlcmsuYWNjb3VudHMuZGV2JA"
  CLERK_SECRET_KEY: "sk_test_FQPaWcJNn422uC3w5MV6PuwBdmNEiI9H209fzKYKe3"
  NEXT_PUBLIC_APP_URL: "https://khuetuan.com"

---
#----------------------------------------------
# Deployment - Quản lý Pod chạy API
#----------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: khuetuan-app
  namespace: khuetuan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khuetuan-app
  template:
    metadata:
      labels:
        app: khuetuan-app
    spec:
      containers:
        - name: khuetuan-app
          image: docker.io/quochau151/khuetuan:main-b863dad
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: khuetuan-config

---
#----------------------------------------------
# Service - Expose API ra ngoài cluster
#----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: khuetuan-service
  namespace: khuetuan
  labels:
    app: khuetuan
    component: service
spec:
  selector:
    app: khuetuan-app
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP

---
#----------------------------------------------
# Ingress - Expose Service ra internet
#----------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: khuetuan-ingress
  namespace: khuetuan
  labels:
    app: khuetuan
    component: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: khuetuan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: khuetuan-service
                port:
                  number: 80
